# Generated by Django 3.2.10 on 2022-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urldb',
            fields=[
                ('data_url_str', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('data_long_url', models.CharField(max_length=200)),
            ],
        ),
    ]
